# Generated by Django 4.1.3 on 2022-11-15 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mod',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'MEDIUM'), ('low', 'LOW')], max_length=6, null=True),
        ),
    ]
